using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.6.801.4115")]
[assembly: AssemblyFileVersionAttribute("0.6.801.4115")]
[assembly: AssemblyCopyrightAttribute("Copyright © Stephen Czetty 2010-2011")]

